#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitersWebApplication.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RecruitersDB")]
	public partial class RecruitersDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRecruiter(Recruiter instance);
    partial void UpdateRecruiter(Recruiter instance);
    partial void DeleteRecruiter(Recruiter instance);
    #endregion
		
		public RecruitersDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RecruitersDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RecruitersDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RecruitersDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RecruitersDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RecruitersDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Recruiter> Recruiters
		{
			get
			{
				return this.GetTable<Recruiter>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sprocAddRecruiter")]
		public int sprocAddRecruiter([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyName", DbType="NVarChar(80)")] string companyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyWebsite", DbType="NVarChar(120)")] string companyWebsite, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanySize", DbType="NVarChar(35)")] string companySize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyLinkedInUrl", DbType="NVarChar(120)")] string companyLinkedInUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyLinkedInId", DbType="Int")] System.Nullable<int> companyLinkedInId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanySpecialists", DbType="NVarChar(450)")] string companySpecialists, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryType", DbType="NVarChar(30)")] string categoryType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OfficeLocation", DbType="NVarChar(50)")] string officeLocation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactNumber", DbType="NVarChar(20)")] string contactNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactEmail", DbType="NVarChar(110)")] string contactEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TwitterId", DbType="NVarChar(80)")] string twitterId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), companyName, companyWebsite, companySize, companyLinkedInUrl, companyLinkedInId, companySpecialists, categoryType, officeLocation, contactNumber, contactEmail, twitterId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sprocUpdateRecruiter")]
		public int sprocUpdateRecruiter([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyName", DbType="NVarChar(80)")] string companyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyWebsite", DbType="NVarChar(120)")] string companyWebsite, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanySize", DbType="NVarChar(15)")] string companySize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyLinkedInUrl", DbType="NVarChar(120)")] string companyLinkedInUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyLinkedInId", DbType="Int")] System.Nullable<int> companyLinkedInId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanySpecialists", DbType="NVarChar(250)")] string companySpecialists, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryType", DbType="NVarChar(30)")] string categoryType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OfficeLocation", DbType="NVarChar(50)")] string officeLocation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactNumber", DbType="NVarChar(20)")] string contactNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactEmail", DbType="NVarChar(110)")] string contactEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TwitterId", DbType="NVarChar(80)")] string twitterId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, companyName, companyWebsite, companySize, companyLinkedInUrl, companyLinkedInId, companySpecialists, categoryType, officeLocation, contactNumber, contactEmail, twitterId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sprocDeleteRecruiter")]
		public int sprocDeleteRecruiter([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sprocGetAdvancedFilteredRecruiterDetails")]
		public ISingleResult<sprocGetAdvancedFilteredRecruiterDetailsResult> sprocGetAdvancedFilteredRecruiterDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyName", DbType="NVarChar(80)")] string companyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanySpecialists", DbType="NVarChar(450)")] string companySpecialists, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryType", DbType="NVarChar(30)")] string categoryType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OfficeLocation", DbType="NVarChar(50)")] string officeLocation)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), companyName, companySpecialists, categoryType, officeLocation);
			return ((ISingleResult<sprocGetAdvancedFilteredRecruiterDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sprocGetCategoryType")]
		public ISingleResult<sprocGetCategoryTypeResult> sprocGetCategoryType()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sprocGetCategoryTypeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sprocGetCompanySpecialists")]
		public ISingleResult<sprocGetCompanySpecialistsResult> sprocGetCompanySpecialists()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sprocGetCompanySpecialistsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sprocGetOfficeLocation")]
		public ISingleResult<sprocGetOfficeLocationResult> sprocGetOfficeLocation()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sprocGetOfficeLocationResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sprocGetRecruiterDetail")]
		public ISingleResult<sprocGetRecruiterDetailResult> sprocGetRecruiterDetail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<sprocGetRecruiterDetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sprocGetRecruiterNames")]
		public ISingleResult<sprocGetRecruiterNamesResult> sprocGetRecruiterNames([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchString", DbType="VarChar(80)")] string searchString)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchString);
			return ((ISingleResult<sprocGetRecruiterNamesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sprocGetRecruiters")]
		public ISingleResult<sprocGetRecruitersResult> sprocGetRecruiters()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sprocGetRecruitersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sprocGetFilteredRecruiterDetails")]
		public ISingleResult<sprocGetFilteredRecruiterDetailsResult> sprocGetFilteredRecruiterDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyName", DbType="NVarChar(80)")] string companyName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), companyName);
			return ((ISingleResult<sprocGetFilteredRecruiterDetailsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recruiters")]
	public partial class Recruiter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CompanyName;
		
		private string _CompanyWebsite;
		
		private string _CompanySize;
		
		private string _CompanyLinkedInUrl;
		
		private int _CompanyLinkedInId;
		
		private string _CompanySpecialists;
		
		private string _CategoryType;
		
		private string _OfficeLocation;
		
		private string _ContactNumber;
		
		private string _ContactEmail;
		
		private string _TwitterId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnCompanyWebsiteChanging(string value);
    partial void OnCompanyWebsiteChanged();
    partial void OnCompanySizeChanging(string value);
    partial void OnCompanySizeChanged();
    partial void OnCompanyLinkedInUrlChanging(string value);
    partial void OnCompanyLinkedInUrlChanged();
    partial void OnCompanyLinkedInIdChanging(int value);
    partial void OnCompanyLinkedInIdChanged();
    partial void OnCompanySpecialistsChanging(string value);
    partial void OnCompanySpecialistsChanged();
    partial void OnCategoryTypeChanging(string value);
    partial void OnCategoryTypeChanged();
    partial void OnOfficeLocationChanging(string value);
    partial void OnOfficeLocationChanged();
    partial void OnContactNumberChanging(string value);
    partial void OnContactNumberChanged();
    partial void OnContactEmailChanging(string value);
    partial void OnContactEmailChanged();
    partial void OnTwitterIdChanging(string value);
    partial void OnTwitterIdChanged();
    #endregion
		
		public Recruiter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyWebsite", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string CompanyWebsite
		{
			get
			{
				return this._CompanyWebsite;
			}
			set
			{
				if ((this._CompanyWebsite != value))
				{
					this.OnCompanyWebsiteChanging(value);
					this.SendPropertyChanging();
					this._CompanyWebsite = value;
					this.SendPropertyChanged("CompanyWebsite");
					this.OnCompanyWebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySize", DbType="NVarChar(35) NOT NULL", CanBeNull=false)]
		public string CompanySize
		{
			get
			{
				return this._CompanySize;
			}
			set
			{
				if ((this._CompanySize != value))
				{
					this.OnCompanySizeChanging(value);
					this.SendPropertyChanging();
					this._CompanySize = value;
					this.SendPropertyChanged("CompanySize");
					this.OnCompanySizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyLinkedInUrl", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string CompanyLinkedInUrl
		{
			get
			{
				return this._CompanyLinkedInUrl;
			}
			set
			{
				if ((this._CompanyLinkedInUrl != value))
				{
					this.OnCompanyLinkedInUrlChanging(value);
					this.SendPropertyChanging();
					this._CompanyLinkedInUrl = value;
					this.SendPropertyChanged("CompanyLinkedInUrl");
					this.OnCompanyLinkedInUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyLinkedInId", DbType="Int NOT NULL")]
		public int CompanyLinkedInId
		{
			get
			{
				return this._CompanyLinkedInId;
			}
			set
			{
				if ((this._CompanyLinkedInId != value))
				{
					this.OnCompanyLinkedInIdChanging(value);
					this.SendPropertyChanging();
					this._CompanyLinkedInId = value;
					this.SendPropertyChanged("CompanyLinkedInId");
					this.OnCompanyLinkedInIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySpecialists", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
		public string CompanySpecialists
		{
			get
			{
				return this._CompanySpecialists;
			}
			set
			{
				if ((this._CompanySpecialists != value))
				{
					this.OnCompanySpecialistsChanging(value);
					this.SendPropertyChanging();
					this._CompanySpecialists = value;
					this.SendPropertyChanged("CompanySpecialists");
					this.OnCompanySpecialistsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryType", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CategoryType
		{
			get
			{
				return this._CategoryType;
			}
			set
			{
				if ((this._CategoryType != value))
				{
					this.OnCategoryTypeChanging(value);
					this.SendPropertyChanging();
					this._CategoryType = value;
					this.SendPropertyChanged("CategoryType");
					this.OnCategoryTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeLocation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OfficeLocation
		{
			get
			{
				return this._OfficeLocation;
			}
			set
			{
				if ((this._OfficeLocation != value))
				{
					this.OnOfficeLocationChanging(value);
					this.SendPropertyChanging();
					this._OfficeLocation = value;
					this.SendPropertyChanged("OfficeLocation");
					this.OnOfficeLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this.OnContactNumberChanging(value);
					this.SendPropertyChanging();
					this._ContactNumber = value;
					this.SendPropertyChanged("ContactNumber");
					this.OnContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="NVarChar(110) NOT NULL", CanBeNull=false)]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this.OnContactEmailChanging(value);
					this.SendPropertyChanging();
					this._ContactEmail = value;
					this.SendPropertyChanged("ContactEmail");
					this.OnContactEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwitterId", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string TwitterId
		{
			get
			{
				return this._TwitterId;
			}
			set
			{
				if ((this._TwitterId != value))
				{
					this.OnTwitterIdChanging(value);
					this.SendPropertyChanging();
					this._TwitterId = value;
					this.SendPropertyChanged("TwitterId");
					this.OnTwitterIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sprocGetAdvancedFilteredRecruiterDetailsResult
	{
		
		private string _CompanyName;
		
		private string _CompanyWebsite;
		
		private string _CompanySize;
		
		private string _CompanyLinkedInUrl;
		
		private int _CompanyLinkedInId;
		
		private string _CompanySpecialists;
		
		private string _CategoryType;
		
		private string _OfficeLocation;
		
		private string _ContactNumber;
		
		private string _ContactEmail;
		
		private string _TwitterId;
		
		public sprocGetAdvancedFilteredRecruiterDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this._CompanyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyWebsite", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string CompanyWebsite
		{
			get
			{
				return this._CompanyWebsite;
			}
			set
			{
				if ((this._CompanyWebsite != value))
				{
					this._CompanyWebsite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySize", DbType="NVarChar(35) NOT NULL", CanBeNull=false)]
		public string CompanySize
		{
			get
			{
				return this._CompanySize;
			}
			set
			{
				if ((this._CompanySize != value))
				{
					this._CompanySize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyLinkedInUrl", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string CompanyLinkedInUrl
		{
			get
			{
				return this._CompanyLinkedInUrl;
			}
			set
			{
				if ((this._CompanyLinkedInUrl != value))
				{
					this._CompanyLinkedInUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyLinkedInId", DbType="Int NOT NULL")]
		public int CompanyLinkedInId
		{
			get
			{
				return this._CompanyLinkedInId;
			}
			set
			{
				if ((this._CompanyLinkedInId != value))
				{
					this._CompanyLinkedInId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySpecialists", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
		public string CompanySpecialists
		{
			get
			{
				return this._CompanySpecialists;
			}
			set
			{
				if ((this._CompanySpecialists != value))
				{
					this._CompanySpecialists = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryType", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CategoryType
		{
			get
			{
				return this._CategoryType;
			}
			set
			{
				if ((this._CategoryType != value))
				{
					this._CategoryType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeLocation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OfficeLocation
		{
			get
			{
				return this._OfficeLocation;
			}
			set
			{
				if ((this._OfficeLocation != value))
				{
					this._OfficeLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this._ContactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="NVarChar(110) NOT NULL", CanBeNull=false)]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this._ContactEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwitterId", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string TwitterId
		{
			get
			{
				return this._TwitterId;
			}
			set
			{
				if ((this._TwitterId != value))
				{
					this._TwitterId = value;
				}
			}
		}
	}
	
	public partial class sprocGetCategoryTypeResult
	{
		
		private string _CategoryType;
		
		public sprocGetCategoryTypeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryType", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CategoryType
		{
			get
			{
				return this._CategoryType;
			}
			set
			{
				if ((this._CategoryType != value))
				{
					this._CategoryType = value;
				}
			}
		}
	}
	
	public partial class sprocGetCompanySpecialistsResult
	{
		
		private string _CompanySpecialists;
		
		public sprocGetCompanySpecialistsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySpecialists", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
		public string CompanySpecialists
		{
			get
			{
				return this._CompanySpecialists;
			}
			set
			{
				if ((this._CompanySpecialists != value))
				{
					this._CompanySpecialists = value;
				}
			}
		}
	}
	
	public partial class sprocGetOfficeLocationResult
	{
		
		private string _OfficeLocation;
		
		public sprocGetOfficeLocationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeLocation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OfficeLocation
		{
			get
			{
				return this._OfficeLocation;
			}
			set
			{
				if ((this._OfficeLocation != value))
				{
					this._OfficeLocation = value;
				}
			}
		}
	}
	
	public partial class sprocGetRecruiterDetailResult
	{
		
		private string _CompanyName;
		
		private string _CompanyWebsite;
		
		private string _CompanySize;
		
		private string _CompanyLinkedInUrl;
		
		private int _CompanyLinkedInId;
		
		private string _CompanySpecialists;
		
		private string _CategoryType;
		
		private string _OfficeLocation;
		
		private string _ContactNumber;
		
		private string _ContactEmail;
		
		private string _TwitterId;
		
		public sprocGetRecruiterDetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this._CompanyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyWebsite", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string CompanyWebsite
		{
			get
			{
				return this._CompanyWebsite;
			}
			set
			{
				if ((this._CompanyWebsite != value))
				{
					this._CompanyWebsite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySize", DbType="NVarChar(35) NOT NULL", CanBeNull=false)]
		public string CompanySize
		{
			get
			{
				return this._CompanySize;
			}
			set
			{
				if ((this._CompanySize != value))
				{
					this._CompanySize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyLinkedInUrl", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string CompanyLinkedInUrl
		{
			get
			{
				return this._CompanyLinkedInUrl;
			}
			set
			{
				if ((this._CompanyLinkedInUrl != value))
				{
					this._CompanyLinkedInUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyLinkedInId", DbType="Int NOT NULL")]
		public int CompanyLinkedInId
		{
			get
			{
				return this._CompanyLinkedInId;
			}
			set
			{
				if ((this._CompanyLinkedInId != value))
				{
					this._CompanyLinkedInId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySpecialists", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
		public string CompanySpecialists
		{
			get
			{
				return this._CompanySpecialists;
			}
			set
			{
				if ((this._CompanySpecialists != value))
				{
					this._CompanySpecialists = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryType", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CategoryType
		{
			get
			{
				return this._CategoryType;
			}
			set
			{
				if ((this._CategoryType != value))
				{
					this._CategoryType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeLocation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OfficeLocation
		{
			get
			{
				return this._OfficeLocation;
			}
			set
			{
				if ((this._OfficeLocation != value))
				{
					this._OfficeLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this._ContactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="NVarChar(110) NOT NULL", CanBeNull=false)]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this._ContactEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwitterId", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string TwitterId
		{
			get
			{
				return this._TwitterId;
			}
			set
			{
				if ((this._TwitterId != value))
				{
					this._TwitterId = value;
				}
			}
		}
	}
	
	public partial class sprocGetRecruiterNamesResult
	{
		
		private string _CompanyName;
		
		public sprocGetRecruiterNamesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this._CompanyName = value;
				}
			}
		}
	}
	
	public partial class sprocGetRecruitersResult
	{
		
		private string _CompanyName;
		
		private string _CompanyWebsite;
		
		private string _CompanySize;
		
		private string _CompanyLinkedInUrl;
		
		private int _CompanyLinkedInId;
		
		private string _CompanySpecialists;
		
		private string _CategoryType;
		
		private string _OfficeLocation;
		
		private string _ContactNumber;
		
		private string _ContactEmail;
		
		private string _TwitterId;
		
		public sprocGetRecruitersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this._CompanyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyWebsite", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string CompanyWebsite
		{
			get
			{
				return this._CompanyWebsite;
			}
			set
			{
				if ((this._CompanyWebsite != value))
				{
					this._CompanyWebsite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySize", DbType="NVarChar(35) NOT NULL", CanBeNull=false)]
		public string CompanySize
		{
			get
			{
				return this._CompanySize;
			}
			set
			{
				if ((this._CompanySize != value))
				{
					this._CompanySize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyLinkedInUrl", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string CompanyLinkedInUrl
		{
			get
			{
				return this._CompanyLinkedInUrl;
			}
			set
			{
				if ((this._CompanyLinkedInUrl != value))
				{
					this._CompanyLinkedInUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyLinkedInId", DbType="Int NOT NULL")]
		public int CompanyLinkedInId
		{
			get
			{
				return this._CompanyLinkedInId;
			}
			set
			{
				if ((this._CompanyLinkedInId != value))
				{
					this._CompanyLinkedInId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySpecialists", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
		public string CompanySpecialists
		{
			get
			{
				return this._CompanySpecialists;
			}
			set
			{
				if ((this._CompanySpecialists != value))
				{
					this._CompanySpecialists = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryType", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CategoryType
		{
			get
			{
				return this._CategoryType;
			}
			set
			{
				if ((this._CategoryType != value))
				{
					this._CategoryType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeLocation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OfficeLocation
		{
			get
			{
				return this._OfficeLocation;
			}
			set
			{
				if ((this._OfficeLocation != value))
				{
					this._OfficeLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this._ContactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="NVarChar(110) NOT NULL", CanBeNull=false)]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this._ContactEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwitterId", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string TwitterId
		{
			get
			{
				return this._TwitterId;
			}
			set
			{
				if ((this._TwitterId != value))
				{
					this._TwitterId = value;
				}
			}
		}
	}
	
	public partial class sprocGetFilteredRecruiterDetailsResult
	{
		
		private string _CompanyName;
		
		private string _CompanyWebsite;
		
		private string _CompanySize;
		
		private string _CompanyLinkedInUrl;
		
		private int _CompanyLinkedInId;
		
		private string _CompanySpecialists;
		
		private string _CategoryType;
		
		private string _OfficeLocation;
		
		private string _ContactNumber;
		
		private string _ContactEmail;
		
		private string _TwitterId;
		
		public sprocGetFilteredRecruiterDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this._CompanyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyWebsite", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string CompanyWebsite
		{
			get
			{
				return this._CompanyWebsite;
			}
			set
			{
				if ((this._CompanyWebsite != value))
				{
					this._CompanyWebsite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySize", DbType="NVarChar(35) NOT NULL", CanBeNull=false)]
		public string CompanySize
		{
			get
			{
				return this._CompanySize;
			}
			set
			{
				if ((this._CompanySize != value))
				{
					this._CompanySize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyLinkedInUrl", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string CompanyLinkedInUrl
		{
			get
			{
				return this._CompanyLinkedInUrl;
			}
			set
			{
				if ((this._CompanyLinkedInUrl != value))
				{
					this._CompanyLinkedInUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyLinkedInId", DbType="Int NOT NULL")]
		public int CompanyLinkedInId
		{
			get
			{
				return this._CompanyLinkedInId;
			}
			set
			{
				if ((this._CompanyLinkedInId != value))
				{
					this._CompanyLinkedInId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySpecialists", DbType="NVarChar(450) NOT NULL", CanBeNull=false)]
		public string CompanySpecialists
		{
			get
			{
				return this._CompanySpecialists;
			}
			set
			{
				if ((this._CompanySpecialists != value))
				{
					this._CompanySpecialists = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryType", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CategoryType
		{
			get
			{
				return this._CategoryType;
			}
			set
			{
				if ((this._CategoryType != value))
				{
					this._CategoryType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeLocation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OfficeLocation
		{
			get
			{
				return this._OfficeLocation;
			}
			set
			{
				if ((this._OfficeLocation != value))
				{
					this._OfficeLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this._ContactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="NVarChar(110) NOT NULL", CanBeNull=false)]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this._ContactEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwitterId", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string TwitterId
		{
			get
			{
				return this._TwitterId;
			}
			set
			{
				if ((this._TwitterId != value))
				{
					this._TwitterId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
